domain_path: C:\Users\alumn\Documents\UNSAM\PFI\Arty_TDC\Vitis_WorkSpace\platform_v2_1\export\platform_v2_1\sw\standalone_microblaze_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
